# -*- coding: utf-8 -*-
"""OraculoGramatical.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mMuIVy65VnQ3JtxZTt4zKYSIeFGheI7e
"""

import streamlit as st
import pandas as pd
from sklearn.tree import DecisionTreeClassifier
import os

# Cargar el dataset
@st.cache_data
def cargar_datos():
    if os.path.exists("frases_dativo_acusativo.csv"):
       return pd.read_csv("frases_dativo_acusativo.csv", encoding="latin1")

    else:
        return pd.DataFrame(columns=["sujeto", "verbo", "preposición", "objeto", "caso", "recibe_accion", "beneficiario", "prep_movimiento"])

df = cargar_datos()

# Entrenar el modelo
if not df.empty:
    X = df[["recibe_accion", "beneficiario", "prep_movimiento"]]
    y = df["caso"]
    modelo = DecisionTreeClassifier()
    modelo.fit(X, y)
else:
    modelo = None

# Preposiciones dativas
preposiciones_dativas = [
    "aus", "bei", "mit", "nach", "seit", "von", "zu",
    "außer", "gegenüber", "entgegen", "gemäß"
]

st.title("📚 Oráculo Gramatical: ¿Dativo o Acusativo?")
st.write("Introduce una frase en alemán y responde algunas preguntas para predecir el caso gramatical.")

frase = st.text_input("✍️ Escribe tu frase en alemán:")
prep = st.text_input("📌 ¿Cuál es la preposición principal de la frase? (Escribe '-' si no hay):").strip().lower()

if frase:
    if prep in preposiciones_dativas:
        st.success(f"La preposición '{prep}' exige **DATIVO** por regla gramatical.")
        prediccion = "dativo"
    elif modelo:
        st.write("Ahora responde estas preguntas sobre la función del objeto en tu frase:")
        r = st.radio("1️⃣ ¿El sustantivo (objeto) recibe directamente la acción del verbo?", [1, 0], format_func=lambda x: "Sí" if x == 1 else "No")
        b = st.radio("2️⃣ ¿El sustantivo es el destinatario o beneficiario de la acción?", [1, 0], format_func=lambda x: "Sí" if x == 1 else "No")
        m = st.radio("3️⃣ ¿La preposición indica movimiento o dirección?", [1, 0], format_func=lambda x: "Sí" if x == 1 else "No")

        if st.button("🔮 Predecir"):
            prediccion = modelo.predict([[r, b, m]])[0]
            st.markdown(f"### ✨ El Oráculo gramatical predice: **{prediccion.upper()}**")

            confirma = st.radio("¿Es correcta esta predicción?", ["sí", "no"])
            if confirma == "no":
                caso_real = st.selectbox("¿Cuál es el caso correcto?", ["dativo", "acusativo"])
                nueva_fila = pd.DataFrame([{
                    "sujeto": "-", "verbo": "-", "preposición": prep, "objeto": frase,
                    "caso": caso_real, "recibe_accion": r, "beneficiario": b, "prep_movimiento": m
                }])
                df = pd.concat([df, nueva_fila], ignore_index=True)
                df.to_csv("frases_dativo_acusativo.csv", index=False, encoding="utf-8")
                st.success("✅ Nuevo ejemplo añadido. El Oráculo ha aprendido algo nuevo.")
    else:
        st.warning("⚠️ No hay suficientes datos para entrenar el modelo. Agrega ejemplos primero.")